// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/addressbook.proto

package com.wdbyte.tool.protos;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wdbyte.protobuf.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.wdbyte.protobuf.Person people = 1;</code>
   */
  java.util.List<com.wdbyte.tool.protos.Person> 
      getPeopleList();
  /**
   * <code>repeated .com.wdbyte.protobuf.Person people = 1;</code>
   */
  com.wdbyte.tool.protos.Person getPeople(int index);
  /**
   * <code>repeated .com.wdbyte.protobuf.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .com.wdbyte.protobuf.Person people = 1;</code>
   */
  java.util.List<? extends com.wdbyte.tool.protos.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .com.wdbyte.protobuf.Person people = 1;</code>
   */
  com.wdbyte.tool.protos.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
